services:
  postgres:
    image: postgres:18
    container_name: postgres_db
    environment:
      POSTGRES_DB: ppls
      POSTGRES_USER: ppls
      POSTGRES_PASSWORD: ppls
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ppls -d ppls" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
