<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\PaperlessREST.Dal\PaperlessREST.Dal.csproj" />
      <ProjectReference Include="..\PaperlessREST.Models\PaperlessREST.Models.csproj" />
    </ItemGroup>

</Project>
